### PR TITLE
Add `--branch-name` argument

### PR DESCRIPTION
**Pull request by blueyed**
Fixes https://github.com/anarcat/bup-cron/issues/19

### CODE REVIEW

**Comment by anarcat** [comment]
hmm... so the reason the path is there is that if you supply multiple paths, it makes it possible to access them independently. otherwise they get all garbled up in the same directory... no?

plus, it seems the two options override each other: i think a check should be made to error out if both options are configured.

**Comment by blueyed** [comment]
> so the reason the path is there is that if you supply multiple paths, it makes it possible to access them independently. otherwise they get all garbled up in the same directory... no?

They would end up in the same branch, yes (AFAIK).
The option is really meant to be used with a single source/path, e.g. I'd like to name the "/" "root" and "/home" "home".

> plus, it seems the two options override each other: i think a check should be made to error out if both options are configured.

Yes, I've looked into it, but found no quick way to check if `args.name` was provided explicitly (since it has a default).

**Comment by anarcat** [comment]
you're right, of course... not sure how to fix that then... maybe through a action or by setting the default by hand outside of argparse... the obvious alternative would be to check if name is different from the default.

**Comment by blueyed** [comment]
> by setting the default by hand outside of argparse

That's the best option probably.  I'll change it to do this.

Any other changes?

**Comment by anarcat** [comment]
not that i can think of!

**Comment by blueyed** [comment]
@anarcat 
I've pushed a fixup-commit.  Let me know if it's good and I'll rebase it - or just do so yourself when merging it.

**Comment by anarcat** [comment]
please rebase and i'll be happy to merge

**Comment by blueyed** [comment]
Rebased it finally.

**Comment by anarcat** [comment]
it would probably make sense to complement this with a clearer description of the distinction between --name and --branch-name...

**Pull request merged**
